// 一纸成文 · 文种库与框架库
// 法定公文依据《党政机关公文处理工作条例》(中办发〔2012〕14号) 15 种
// 事务文书为机关高频材料类型
window.WENZHONG = [
  {
    id: 'tongzhi', name: '通知', cat: '法定公文', free: true, direction: '下行',
    desc: '发布、传达要求下级机关执行和有关单位周知或者执行的事项',
    fields: [
      { key: 'org', label: '发文单位', ph: '如：XX市人民政府办公室', required: true },
      { key: 'docno', label: '发文字号', ph: '如：X政办发〔2026〕12号', required: false },
      { key: 'title', label: '文件标题', ph: '如：关于开展2026年度安全生产大检查的通知', required: true },
      { key: 'to', label: '主送单位', ph: '如：各县（市、区）人民政府，市政府各部门：', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '用几句话说明：背景/目的、主要工作安排、时间要求、责任单位等', required: false, type: 'textarea' },
      { key: 'sign', label: '落款单位（默认同发文单位）', ph: '', required: false },
      { key: 'date', label: '成文日期', ph: '如：2026年9月12日', required: false },
    ],
    framework: [
      '{to}',
      'p|为进一步{目的}，根据{依据}要求，经研究，决定{事项总述}。现将有关事项通知如下：',
      'h1|一、总体要求',
      'p|以{指导思想}为指导，坚持{基本原则}，聚焦{重点领域}，确保{工作目标}。{到时间节点，完成……}',
      'h1|二、主要任务',
      'h2|（一）{任务一名称}',
      'p|由{责任单位}牵头，{具体安排}。{量化要求}。',
      'h2|（二）{任务二名称}',
      'p|由{责任单位}牵头，{具体安排}。',
      'h1|三、保障措施',
      'h2|（一）加强组织领导。', 'p|成立{领导小组名称}，{统筹安排}。',
      'h2|（二）压实工作责任。', 'p|各地各部门要{责任落实要求}。',
      'h2|（三）强化督查考核。', 'p|{督查方式}，对{情形}的，予以{处理方式}。',
      'p|附件：{附件名称}',
    ],
    aiHint: '结构采用"总体要求—主要任务—保障措施"或"目的—范围—具体安排—要求"式；语言庄重平实，多用"要""确保""不得""原则上"等规范表述；涉及数字、时间、责任单位的地方一律用【 】占位符留待用户填写，不得编造具体数据。',
  },
  {
    id: 'qingshi', name: '请示', cat: '法定公文', free: true, direction: '上行',
    desc: '向上级机关请求指示、批准（一文一事，须签发人）',
    fields: [
      { key: 'org', label: '发文单位', ph: '如：XX市工业和信息化局', required: true },
      { key: 'docno', label: '发文字号', ph: '如：X工信发〔2026〕23号', required: false },
      { key: 'issuer', label: '签发人', ph: '如：张三', required: false },
      { key: 'title', label: '文件标题', ph: '如：关于申请XX项目专项资金的请示', required: true },
      { key: 'to', label: '主送单位（只能有一个）', ph: '如：市人民政府：', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '说明：请示缘由（背景/必要性/依据）、请示事项（具体请求）、资金或事项明细', required: false, type: 'textarea' },
      { key: 'sign', label: '落款单位（默认同发文单位）', ph: '', required: false },
      { key: 'date', label: '成文日期', ph: '如：2026年9月12日', required: false },
    ],
    framework: [
      '{to}',
      'p|{缘由引入：近年来/随着……}。{必要性说明}。{依据文件或现实困难}。',
      'h1|一、基本情况',
      'p|{现状与数据占位【 】}。',
      'h1|二、请示事项',
      'p|恳请{上级机关}{具体请求事项}：一是{……}；二是{……}。',
      'p|以上请示妥否，请批示。',
    ],
    aiHint: '请示必须"一文一事"；缘由充分、事项具体、语气恳切；结尾固定用"以上请示妥否，请批示。"或"特此请示，请予批准。"；不得编造资金数额，一律用【 】占位。',
  },
  {
    id: 'baogao', name: '报告', cat: '法定公文', free: true, direction: '上行',
    desc: '向上级机关汇报工作、反映情况、回复询问',
    fields: [
      { key: 'org', label: '发文单位', ph: '如：XX县教育局', required: true },
      { key: 'docno', label: '发文字号', ph: '', required: false },
      { key: 'issuer', label: '签发人', ph: '', required: false },
      { key: 'title', label: '文件标题', ph: '如：关于2026年上半年重点工作推进情况的报告', required: true },
      { key: 'to', label: '主送单位', ph: '如：市教育局：', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '说明：工作背景、主要做法与成效、存在问题、下一步打算', required: false, type: 'textarea' },
      { key: 'sign', label: '落款单位（默认同发文单位）', ph: '', required: false },
      { key: 'date', label: '成文日期', ph: '', required: false },
    ],
    framework: [
      '{to}',
      'p|{开头引语：根据……要求，现将……情况报告如下}。',
      'h1|一、工作开展情况',
      'h2|（一）{方面一}',
      'p|{做法＋成效，数据用【 】占位}。',
      'h2|（二）{方面二}',
      'p|……',
      'h1|二、存在的主要问题',
      'p|一是{问题一}；二是{问题二}。',
      'h1|三、下一步工作打算',
      'p|{措施安排}。',
      'p|特此报告。',
    ],
    aiHint: '报告以陈述事实为主，不夹带请示事项；常用"（一）（二）（三）"归纳做法；成效表述多用数据支撑（数据一律【 】占位）；结尾用"特此报告。"。',
  },
  {
    id: 'han', name: '函', cat: '法定公文', free: true, direction: '平行',
    desc: '不相隶属机关之间商洽工作、询问和答复问题、请求批准和答复审批事项',
    fields: [
      { key: 'org', label: '发文单位', ph: '如：XX市市场监督管理局', required: true },
      { key: 'docno', label: '发文字号', ph: '', required: false },
      { key: 'title', label: '文件标题', ph: '如：关于商请协助开展XX专项调研的函', required: true },
      { key: 'to', label: '主送单位', ph: '如：XX市公安局：', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '说明：商洽/询问/请求事项、缘由、希望对方做什么、联系方式', required: false, type: 'textarea' },
      { key: 'sign', label: '落款单位（默认同发文单位）', ph: '', required: false },
      { key: 'date', label: '成文日期', ph: '', required: false },
    ],
    framework: [
      '{to}',
      'p|{缘由：为……／因……}，{商洽或请求事项}。{具体说明：时间、范围、需要对方配合的内容}。',
      'p|请予支持为盼。（或：请研究函复。／特此函询，盼复。）',
      'p|联系人：【姓名】　联系电话：【电话】',
    ],
    aiHint: '函是平行文，语气平和得体、相互尊重，忌用命令口吻；结尾视类型选用"请予支持为盼""请研究函复""特此函告"等；事项要素（时间、地点、内容、联系人）写清。',
  },
  {
    id: 'jiyao', name: '会议纪要', cat: '法定公文', free: true, direction: '平/下',
    desc: '记载会议主要情况和议定事项',
    fields: [
      { key: 'org', label: '单位', ph: '如：XX县政府办公室', required: true },
      { key: 'title', label: '纪要标题', ph: '如：XX县政府2026年第9次常务会议纪要', required: true },
      { key: 'meta', label: '会议要素', ph: '时间／地点／主持人／参加人员／记录人（每行一项）', required: true, type: 'textarea' },
      { key: 'points', label: '会议内容与议定事项（AI 拟稿依据）', ph: '用口语把会议讲了什么、定了什么写清楚，AI 转成纪要语言', required: true, type: 'textarea' },
      { key: 'date', label: '日期', ph: '', required: false },
    ],
    framework: [
      'center|{meta 摘要：时间地点主持参加}',
      'p|{会议概述：听取了……汇报，研究了……事项}。',
      'h1|会议指出',
      'p|{会议精神要点}。',
      'h1|会议强调',
      'p|{工作要求}。',
      'h1|会议议定事项',
      'p|一、{议定事项一}；二、{议定事项二}。',
    ],
    aiHint: '纪要采用"会议指出／会议强调／会议议定事项"三段式是安全写法；把口语转成规范书面语；议定事项逐条编号，明确责任单位与时限（不明确的用【 】占位）。',
  },
  {
    id: 'pifu', name: '批复', cat: '法定公文', free: false, direction: '下行',
    desc: '答复下级机关请示事项',
    fields: [
      { key: 'org', label: '发文单位', ph: '', required: true },
      { key: 'docno', label: '发文字号', ph: '', required: false },
      { key: 'title', label: '文件标题', ph: '如：关于同意XX项目立项的批复', required: true },
      { key: 'to', label: '主送单位', ph: '如：你局《关于……的请示》（X发〔2026〕X号）收悉。', required: true },
      { key: 'points', label: '批复意见要点', ph: '', required: true, type: 'textarea' },
      { key: 'sign', label: '落款单位', ph: '', required: false },
      { key: 'date', label: '成文日期', ph: '', required: false },
    ],
    framework: [
      '{to}',
      'p|{引语：你单位《关于……的请示》（〔2026〕X号）收悉。经研究，现批复如下}：',
      'p|{批复意见：同意／原则同意／不同意……}。',
      'p|{要求或提醒事项}。',
    ],
    aiHint: '批复针对性极强，一请示一批复；态度明确（同意/不同意/原则同意），不含糊；可附执行要求。',
  },
  {
    id: 'yijian', name: '意见', cat: '法定公文', free: false, direction: '均',
    desc: '对重要问题提出见解和处理办法',
    fields: [
      { key: 'org', label: '发文单位', ph: '', required: true },
      { key: 'docno', label: '发文字号', ph: '', required: false },
      { key: 'title', label: '文件标题', ph: '如：关于加快推进XX产业高质量发展的实施意见', required: true },
      { key: 'to', label: '主送单位', ph: '', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '', required: false, type: 'textarea' },
      { key: 'sign', label: '落款单位', ph: '', required: false },
      { key: 'date', label: '成文日期', ph: '', required: false },
    ],
    framework: [
      '{to}',
      'p|为{目标}，现就{事项}提出如下意见。',
      'h1|一、总体要求（指导思想、基本原则、主要目标）',
      'h1|二、重点任务',
      'h2|（一）……（二）……（三）……',
      'h1|三、保障措施（组织领导、政策支持、督查考核）',
    ],
    aiHint: '意见讲究系统性：总体要求＋分条任务＋保障措施；目标可量化处用【 】占位；"到202X年"式目标句式常用。',
  },
  {
    id: 'jueding', name: '决定', cat: '法定公文', free: false, direction: '下行',
    desc: '对重要事项作出决策和部署、奖惩有关单位和人员',
    fields: [
      { key: 'org', label: '发文单位', ph: '', required: true },
      { key: 'title', label: '文件标题', ph: '如：关于表彰2025年度先进集体和先进个人的决定', required: true },
      { key: 'to', label: '主送单位', ph: '', required: false },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '', required: true, type: 'textarea' },
      { key: 'sign', label: '落款单位', ph: '', required: false },
      { key: 'date', label: '成文日期', ph: '', required: false },
    ],
    framework: [
      '{to}',
      'p|{缘由与目的}。经{决策程序}研究，决定：',
      'p|一、{决定事项一}。二、{决定事项二}。',
      'p|希望{号召或要求}。',
    ],
    aiHint: '决定短小庄重，直陈决定事项；表彰类决定结尾用"希望受到表彰的单位和个人……"。',
  },
  {
    id: 'tongbao', name: '通报', cat: '法定公文', free: false, direction: '下行',
    desc: '表彰先进、批评错误、传达重要精神和告知重要情况',
    fields: [
      { key: 'org', label: '发文单位', ph: '', required: true },
      { key: 'docno', label: '发文字号', ph: '', required: false },
      { key: 'title', label: '文件标题', ph: '如：关于XX安全生产责任事故处理情况的通报', required: true },
      { key: 'to', label: '主送单位', ph: '', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '', required: true, type: 'textarea' },
      { key: 'sign', label: '落款单位', ph: '', required: false },
      { key: 'date', label: '成文日期', ph: '', required: false },
    ],
    framework: [
      '{to}',
      'p|{事实经过：时间、地点、单位、事件}。',
      'p|{性质认定与原因分析}。',
      'p|{处理决定}。',
      'p|{普遍要求：各地各部门要举一反三……}。',
    ],
    aiHint: '通报重事实与教训；批评类通报措辞严谨，处理决定引用依据（依据用【 】占位）；结尾提出面上要求。',
  },
  {
    id: 'gonggao', name: '公告', cat: '法定公文', free: false, direction: '外',
    desc: '向国内外宣布重要事项或者法定事项',
    fields: [
      { key: 'org', label: '发布单位', ph: '', required: true },
      { key: 'title', label: '公告标题', ph: '', required: true },
      { key: 'points', label: '公告事项要点', ph: '', required: true, type: 'textarea' },
      { key: 'sign', label: '落款单位', ph: '', required: false },
      { key: 'date', label: '发布日期', ph: '', required: false },
    ],
    framework: [
      'p|{公告事项，一段一事，简明扼要}。',
      'p|特此公告。',
    ],
    aiHint: '公告面向国内外，篇幅极简、语句庄重，不加议论；结尾"特此公告。"。',
  },
  {
    id: 'tonggao', name: '通告', cat: '法定公文', free: false, direction: '外',
    desc: '在一定范围内公布应当遵守或者周知的事项',
    fields: [
      { key: 'org', label: '发布单位', ph: '', required: true },
      { key: 'title', label: '通告标题', ph: '', required: true },
      { key: 'points', label: '通告事项要点', ph: '', required: true, type: 'textarea' },
      { key: 'sign', label: '落款单位', ph: '', required: false },
      { key: 'date', label: '发布日期', ph: '', required: false },
    ],
    framework: [
      'p|{缘由：为……，根据……}，现将有关事项通告如下：',
      'p|一、{事项一}。二、{事项二}。三、{事项三}。',
      'p|本通告自发布之日起施行。',
    ],
    aiHint: '通告面向一定范围的社会公众，条款化编排（一、二、三），语言准确无歧义，明确生效时间。',
  },
  {
    id: 'jueyi', name: '决议', cat: '法定公文', free: false, direction: '会议',
    desc: '会议讨论通过的重大决策事项',
    fields: [
      { key: 'org', label: '会议名称', ph: '如：XX市第X届人民代表大会第X次会议', required: true },
      { key: 'title', label: '决议标题', ph: '', required: true },
      { key: 'points', label: '决议内容要点', ph: '', required: true, type: 'textarea' },
      { key: 'date', label: '通过日期', ph: '', required: false },
    ],
    framework: [
      'p|{会议名称}于{日期}审议通过了{事项}。现予公布。',
      'p|{决议核心内容}。',
    ],
    aiHint: '决议以会议名义发布，开头交代"XX会议审议通过"；语气权威、高度概括。',
  },
  {
    id: 'gongbao', name: '公报', cat: '法定公文', free: false, direction: '外',
    desc: '公布重要决定或者重大事项',
    fields: [
      { key: 'org', label: '发布主体', ph: '', required: true },
      { key: 'title', label: '公报标题', ph: '', required: true },
      { key: 'points', label: '公报内容要点', ph: '', required: true, type: 'textarea' },
      { key: 'date', label: '日期', ph: '', required: false },
    ],
    framework: [
      'p|{发布主体与事项概述}。',
      'h1|一、{部分一}',
      'h1|二、{部分二}',
    ],
    aiHint: '公报多为会议公报、统计公报，分部分编排，数据密集（数据【 】占位）。',
  },
  {
    id: 'mingling', name: '命令（令）', cat: '法定公文', free: false, direction: '令',
    desc: '公布行政法规和规章、宣布施行重大强制性措施、批准授予和晋升衔级、嘉奖有关单位和人员',
    fields: [
      { key: 'org', label: '发布机关', ph: '', required: true },
      { key: 'title', label: '命令标题', ph: '', required: true },
      { key: 'points', label: '命令内容要点', ph: '', required: true, type: 'textarea' },
      { key: 'issuer', label: '签署人（行政首长）', ph: '', required: false },
      { key: 'date', label: '签发日期', ph: '', required: false },
    ],
    framework: [
      'p|{命令事项}。',
      'p|此令。',
    ],
    aiHint: '命令强制力最强，篇幅极短，"此令。"结尾；署行政首长职务与姓名。',
  },
  {
    id: 'yian', name: '议案', cat: '法定公文', free: false, direction: '上行',
    desc: '各级人民政府按照法律程序向同级人民代表大会或其常委会提请审议事项',
    fields: [
      { key: 'org', label: '发文单位', ph: '', required: true },
      { key: 'title', label: '议案标题', ph: '如：关于提请审议《XX条例（草案）》的议案', required: true },
      { key: 'to', label: '主送（人大或其常委会）', ph: '', required: true },
      { key: 'points', label: '议案要点', ph: '', required: true, type: 'textarea' },
      { key: 'issuer', label: '签署人', ph: '', required: false },
      { key: 'date', label: '成文日期', ph: '', required: false },
    ],
    framework: [
      '{to}',
      'p|{提请审议事项说明}。现将《……（草案）》提请审议。',
      'p|{起草背景与主要内容}。',
    ],
    aiHint: '议案依法定程序提交，格式严格；正文交代草案起草过程、主要内容、可行性。',
  },
  // ============ 事务文书 ============
  {
    id: 'jianghuagao', name: '讲话稿', cat: '事务文书', free: false, direction: '—',
    desc: '领导在会议、活动上的讲话',
    fields: [
      { key: 'org', label: '讲话人身份', ph: '如：XX局局长 王XX', required: true },
      { key: 'title', label: '讲话场合/标题', ph: '如：在全市营商环境建设大会上的讲话', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '会议背景、想强调的重点、布置的工作、对听众的要求', required: true, type: 'textarea' },
      { key: 'len', label: '预计时长', ph: '如：10分钟（约2500字）', required: false },
      { key: 'date', label: '日期', ph: '', required: false },
    ],
    framework: [
      'center|——在XXX会议上的讲话——',
      'p|同志们：',
      'p|{开场：今天我们召开这次会议，主要任务是……}。',
      'h1|一、{肯定成绩/认清形势}',
      'p|{成绩与问题，一分为二}。',
      'h1|二、{部署重点任务}',
      'h2|（一）……（二）……（三）……',
      'h1|三、{加强领导/抓好落实}',
      'p|{结尾号召}。',
    ],
    aiHint: '讲话稿要有对象感和现场感：称呼"同志们"、设问排比、口语化但庄重；典型句式"刚才，……讲得很好，我完全赞同，我再强调三点"；篇幅按时长折算（1分钟约250字）。',
  },
  {
    id: 'zongjie', name: '工作总结', cat: '事务文书', free: false, direction: '—',
    desc: '单位或个人阶段性工作全面总结',
    fields: [
      { key: 'org', label: '单位/个人', ph: '', required: true },
      { key: 'title', label: '总结标题', ph: '如：2026年上半年工作总结', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '做了哪些工作（分条列出）、取得什么成效（有数据的写数据）、有什么不足、下一步计划', required: true, type: 'textarea' },
      { key: 'date', label: '日期', ph: '', required: false },
    ],
    framework: [
      'p|{总起：今年以来，……坚持以……为指导，……，现将有关情况总结如下}。',
      'h1|一、主要工作开展情况',
      'h2|（一）{方面一}。', 'p|{做法＋成效}。',
      'h2|（二）{方面二}。', 'p|……',
      'h1|二、存在的问题与不足',
      'p|{客观分析，不推责}。',
      'h1|三、下一步工作打算',
      'p|{改进措施与计划}。',
    ],
    aiHint: '总结的黄金结构：成绩讲够（数据化）、问题讲透（具体化）、打算讲实（可操作）；常用"一是二是三是"排比；数据一律【 】占位。',
  },
  {
    id: 'shuzhi', name: '述职报告', cat: '事务文书', free: false, direction: '—',
    desc: '干部考核时陈述任职情况',
    fields: [
      { key: 'org', label: '述职人身份', ph: '如：XX科科长 李XX', required: true },
      { key: 'title', label: '述职标题', ph: '如：2025年度述职报告', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '岗位职责、主要工作与成效、廉政情况、不足与改进', required: true, type: 'textarea' },
      { key: 'date', label: '日期', ph: '', required: false },
    ],
    framework: [
      'p|{总起：一年来，在……领导下，本人立足岗位职责……现将履职情况报告如下}。',
      'h1|一、政治理论学习情况',
      'h1|二、履职尽责主要情况',
      'h1|三、廉洁自律情况',
      'h1|四、存在的不足和改进方向',
    ],
    aiHint: '述职报告第一人称，突出"职"与"绩"的对应；政治建设放在首位；不足部分真诚具体但不致命（1-2条为宜）。',
  },
  {
    id: 'huibao', name: '汇报材料', cat: '事务文书', free: false, direction: '—',
    desc: '向上级领导/检查组汇报工作的材料',
    fields: [
      { key: 'org', label: '汇报单位', ph: '', required: true },
      { key: 'title', label: '汇报标题', ph: '如：关于XX工作情况的汇报', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '', required: true, type: 'textarea' },
      { key: 'date', label: '日期', ph: '', required: false },
    ],
    framework: [
      'p|{开头：尊敬的X组长／各位领导：欢迎……。现将……情况汇报如下}。',
      'h1|一、基本情况',
      'h1|二、主要做法及成效',
      'h1|三、存在的困难和问题',
      'h1|四、意见建议',
    ],
    aiHint: '汇报材料重数据、重实例、重亮点提炼（小标题要"亮"）；对检查组/领导用敬语；问题部分实事求是。',
  },
  {
    id: 'fangan', name: '工作方案', cat: '事务文书', free: false, direction: '—',
    desc: '专项工作的实施安排',
    fields: [
      { key: 'org', label: '发文单位', ph: '', required: true },
      { key: 'title', label: '方案标题', ph: '如：XX市2026年防汛应急工作方案', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '', required: true, type: 'textarea' },
      { key: 'date', label: '日期', ph: '', required: false },
    ],
    framework: [
      'p|为{目标}，结合实际，制定本方案。',
      'h1|一、指导思想',
      'h1|二、工作目标',
      'h1|三、组织机构（成立……领导小组，下设办公室）',
      'h1|四、实施步骤（动员部署阶段／组织实施阶段／总结提升阶段，各阶段写明时间节点）',
      'h1|五、工作要求',
    ],
    aiHint: '方案要可执行：步骤带时间节点、任务带责任单位、要求带督查机制；附件可列任务分解表。',
  },
  {
    id: 'jianbao', name: '信息简报', cat: '事务文书', free: false, direction: '—',
    desc: '机关内部工作动态信息报送',
    fields: [
      { key: 'org', label: '编发单位', ph: '', required: true },
      { key: 'title', label: '信息标题', ph: '如：XX区"三个聚焦"推动营商环境持续优化', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '', required: true, type: 'textarea' },
      { key: 'date', label: '日期', ph: '', required: false },
    ],
    framework: [
      'p|{导语：一句话概括做法与成效}。',
      'h2|一是{做法一}。',
      'h2|二是{做法二}。',
      'h2|三是{做法三}。',
      'p|{成效数据或下一步}。',
    ],
    aiHint: '信息简报是"亮点文体"：标题提炼"数字＋动词"模式（如"三个聚焦""四轮驱动"）；每段"做法＋成效"短平快；总字数通常800-1500字。',
  },
  {
    id: 'xinde', name: '心得体会', cat: '事务文书', free: false, direction: '—',
    desc: '学习培训、会议精神后的心得',
    fields: [
      { key: 'org', label: '作者身份', ph: '', required: true },
      { key: 'title', label: '标题', ph: '如：学习党的二十届三中全会精神心得体会', required: true },
      { key: 'points', label: '核心要点（AI 拟稿依据）', ph: '学了什么、最深的三点感受、结合岗位怎么干', required: true, type: 'textarea' },
      { key: 'date', label: '日期', ph: '', required: false },
    ],
    framework: [
      'p|{总起：通过学习……，我深受教育、倍感振奋。主要有以下三点体会}。',
      'h1|一、{体会一：思想认识层面}',
      'h1|二、{体会二：使命责任层面}',
      'h1|三、{体会三：结合实际怎么干}',
      'p|{结尾：今后将……}。',
    ],
    aiHint: '心得体会忌空对空：每段"认识＋联系岗位实际"；引用原文用【 】占位；结尾落到"怎么做"。',
  },
];
